# Generated by Django 4.0.2 on 2022-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_code',
            field=models.CharField(blank=True, default='C3APM8', max_length=200, null=True),
        ),
    ]
