# Generated by Django 4.0.2 on 2022-02-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_login_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='login_code',
            field=models.CharField(blank=True, default='JP62IL', max_length=200, null=True),
        ),
    ]
